/**
 * YogaAustin - Frontend App
 * Auto-generated by Module Library Assembler with AI
 */
import React, { useState, useEffect } from 'react';
import { BrowserRouter, Routes, Route, Link, useLocation } from 'react-router-dom';
import './theme.css';

// Page imports
import HomePage from './pages/HomePage';
import AboutPage from './pages/AboutPage';
import ServicesPage from './pages/ServicesPage';
import ContactPage from './pages/ContactPage';
import PricingPage from './pages/PricingPage';
import BookingPage from './pages/BookingPage';
import GalleryPage from './pages/GalleryPage';
import TestimonialsPage from './pages/TestimonialsPage';
import FaqPage from './pages/FaqPage';
import BlogPage from './pages/BlogPage';
import TeamPage from './pages/TeamPage';

// Navigation component with mobile support
function Navigation() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [isMobile, setIsMobile] = useState(window.innerWidth < 768);
  const location = useLocation();

  useEffect(() => {
    const handleResize = () => setIsMobile(window.innerWidth < 768);
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  // Close menu when route changes
  useEffect(() => {
    setMenuOpen(false);
  }, [location]);

  const navLinks = [
    { to: '/', label: 'Home' },
    { to: '/about', label: 'About' },
    { to: '/services', label: 'Services' },
    { to: '/contact', label: 'Contact' },
    { to: '/pricing', label: 'Pricing' },
    { to: '/booking', label: 'Booking' },
    { to: '/gallery', label: 'Gallery' },
    { to: '/testimonials', label: 'Testimonials' },
    { to: '/faq', label: 'FAQ' },
    { to: '/blog', label: 'Blog' },
    { to: '/team', label: 'Team' },
  ];

  return (
    <nav style={styles.nav}>
      <Link to="/" style={styles.navBrand}>
        <span style={styles.brandText}>YogaAustin</span>
      </Link>

      {/* Desktop Navigation */}
      {!isMobile && (
        <div style={styles.navLinks}>
          {navLinks.map(link => (
            <Link key={link.to} to={link.to} style={styles.navLink}>{link.label}</Link>
          ))}
        </div>
      )}

      {/* Mobile Hamburger Button */}
      {isMobile && (
        <button
          onClick={() => setMenuOpen(!menuOpen)}
          style={styles.hamburger}
          aria-label="Toggle menu"
        >
          <span style={{
            ...styles.hamburgerLine,
            transform: menuOpen ? 'rotate(45deg) translateY(6px)' : 'none'
          }} />
          <span style={{
            ...styles.hamburgerLine,
            opacity: menuOpen ? 0 : 1
          }} />
          <span style={{
            ...styles.hamburgerLine,
            transform: menuOpen ? 'rotate(-45deg) translateY(-6px)' : 'none'
          }} />
        </button>
      )}

      {/* Mobile Dropdown Menu */}
      {isMobile && menuOpen && (
        <div style={styles.mobileMenu}>
          {navLinks.map(link => (
            <Link
              key={link.to}
              to={link.to}
              style={styles.mobileNavLink}
              onClick={() => setMenuOpen(false)}
            >
              {link.label}
            </Link>
          ))}
        </div>
      )}
    </nav>
  );
}

function App() {
  return (
    <BrowserRouter>
      <div style={styles.app}>
        <Navigation />
        
        {/* Main Content */}
        <main style={styles.main}>
          <Routes>
            <Route path="/" element={<HomePage />} />
            <Route path="/about" element={<AboutPage />} />
            <Route path="/services" element={<ServicesPage />} />
            <Route path="/contact" element={<ContactPage />} />
            <Route path="/pricing" element={<PricingPage />} />
            <Route path="/booking" element={<BookingPage />} />
            <Route path="/gallery" element={<GalleryPage />} />
            <Route path="/testimonials" element={<TestimonialsPage />} />
            <Route path="/faq" element={<FaqPage />} />
            <Route path="/blog" element={<BlogPage />} />
            <Route path="/team" element={<TeamPage />} />
          </Routes>
        </main>
        
        {/* Footer */}
        <footer style={styles.footer}>
          <p>© 2026 YogaAustin. All rights reserved.</p>
        </footer>
      </div>
    </BrowserRouter>
  );
}

const styles = {
  app: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    background: '#ffffff',
    color: '#3b0764',
    fontFamily: "system-ui, -apple-system, sans-serif",
  },
  nav: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 24px',
    background: '#ffffff',
    borderBottom: '1px solid rgba(10, 22, 40, 0.1)',
    position: 'sticky',
    top: 0,
    zIndex: 1000,
    flexWrap: 'nowrap',
    minHeight: '60px',
    boxSizing: 'border-box',
  },
  navBrand: {
    textDecoration: 'none',
    flexShrink: 0,
  },
  brandText: {
    fontSize: '20px',
    fontWeight: '400',
    fontFamily: "'Cormorant Garamond', Georgia, serif",
    color: '#4c1d95',
    letterSpacing: '1px',
  },
  navLinks: {
    display: 'flex',
    gap: '24px',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  navLink: {
    color: '#6b7280',
    textDecoration: 'none',
    fontSize: '13px',
    fontWeight: '500',
    letterSpacing: '0.5px',
    textTransform: 'uppercase',
    transition: 'color 0.2s',
    whiteSpace: 'nowrap',
  },
  hamburger: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: '40px',
    height: '40px',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    padding: '8px',
    gap: '5px',
    zIndex: 1001,
  },
  hamburgerLine: {
    width: '24px',
    height: '2px',
    background: '#4c1d95',
    transition: 'all 0.3s ease',
  },
  mobileMenu: {
    position: 'absolute',
    top: '60px',
    left: 0,
    right: 0,
    background: '#ffffff',
    borderBottom: '1px solid rgba(10, 22, 40, 0.1)',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
    display: 'flex',
    flexDirection: 'column',
    padding: '16px 0',
    zIndex: 999,
  },
  mobileNavLink: {
    color: '#3b0764',
    textDecoration: 'none',
    fontSize: '16px',
    fontWeight: '500',
    padding: '14px 24px',
    borderBottom: '1px solid rgba(10, 22, 40, 0.05)',
    transition: 'background 0.2s',
  },
  main: {
    flex: 1,
  },
  footer: {
    padding: '40px 24px',
    background: '#4c1d95',
    textAlign: 'center',
    color: 'rgba(255,255,255,0.6)',
    fontSize: '14px',
    letterSpacing: '1px',
  },
};

export default App;